spring:
  application:
    name: MoviesPlatform
  profiles:
    active: local

  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movies_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 60000


      # MinIO Konfiqurasiyası
  minio:
        url: http://localhost:9000
        access-key: minioadmin
        secret-key: minioadmin
        bucket-name: movie-videos

  # File Upload Configuration (Video üçün vacibdir)
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  # JPA and Hibernate configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  # Liquibase Configuration
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  # Redis Data configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# Custom Application Parametrlər
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:secure-and-very-long-secret-key-for-jwt-at-least-32-chars}
      expiration-ms: 86400000 # 1 gün



# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

server:
  port: 8081

# Caching Configuration
cache:
  redis:
    paymentmethod:
      ttl: 3600
    user:
      ttl: 10

# Logging Configuration
logging:
  level:
    root: info
    org.example.moviesplatform: debug
    org.hibernate.SQL: info # SQL loglarını çoxaldıb konsolu doldurmamaq üçün info etdim