spring:
  application:
    name: MoviesPlatform
  profiles:
    active: local

  # JPA and Hibernate configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  # Database Configuration - Hikari
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 6
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 60000

  # Redis Data configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Liquibase Configuration
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs

# Server port
server:
  port: 8081

# Custom Application parameters
application:
  whitelist:
    user: 9

# Caching Configuration
cache:
  redis:
    paymentmethod:
      ttl: 3600 # seconds
    user:
      ttl: 10 # seconds

# Logging Configuration
logging:
  level:
    root: info
    com.texnoera: debug